version: '3'

networks:
  app-tier:
    driver: bridge

services:
  master:
    image: redis
    container_name: redis-master
    ports:
      - 6380:6379
    command: redis-server  --requirepass redis_pwd  --masterauth redis_pwd   --replica-announce-ip 192.168.1.184   --replica-announce-port  6380
    networks:
      - app-tier
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --masterauth redis_pwd  --requirepass redis_pwd  --replica-announce-ip 192.168.1.184  --replica-announce-port  6381
    depends_on:
      - master
    networks:
      - app-tier
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --masterauth redis_pwd --requirepass redis_pwd  --replica-announce-ip 192.168.1.184  --replica-announce-port  6382
    depends_on:
      - master
    networks:
      - app-tier

  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - master
      - slave1
      - slave2
    networks:
      - app-tier
  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - master
      - slave1
      - slave2
    networks:
      - app-tier
  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - master
      - slave1
      - slave2
    networks:
      - app-tier
